name: Frontend Build-Only Pipeline

on:
  push:
    
  pull_request:
        branches:
          - lunar-1
          - lunar-B1
jobs:
  build:
     name: Build-status-check
     runs-on: ubuntu-latest
     steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node@16.13.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
        
      - name: Install NPM Dependencies
        run:  npm install --force  
               

      - name: Install Angular@9
        run: npm install -g @angular/cli
    #   - name: Remove Existing 'ng-uikit-pro-standard'
    #     run:  rm -rf node_modules/ng-uikit-pro-standard

    #   - name: Copy New 'ng-uikit-pro-standard'
    #     run: |
    #          mkdir -p node_modules
    #          cp -r ng-uikit-pro-standard node_modules/
      - name: Build Code 
        run:   ng build
        #   if [ $? -eq 0 ]; then
        #      echo "::set-output name=status::success"
        #   else
        #   echo "::set-output name=status::failure"
        #   echo "Build has been failed and PR is getting close"
        #   PR_NUMBER="${{ github.event.pull_request.number }}"
        #   API_URL="https://api.github.com/repos/axmaijaz/repo1/pulls/$PR_NUMBER"
        #   PAYLOAD='{"state":"closed"}'

      
  