name: Release & Deployment Pipeline

on:
    workflow_run:
        workflows: ["Frontend Build-Only Pipeline"] 
        types:
            - completed
    pull_request_review:
        types:
            - submitted
    # workflow_dispatch:
    #     inputs:
    #         releaseType:
    #             description: 'Where to release (Staging or Prod)?'
    #             required: true
    #             default: 'staging'
    workflow_dispatch:
      inputs:
        production_approval:
          description: 'Approve Production Deployment'
          required: true
          default: 'false'
jobs:
    deploy_staging:
        name: Deploy to Staging
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
    
        # Add your build and deployment steps for staging here.
        # For example:
        - name: Build and Deploy Staging
          run: |
            # Replace with your build and deployment commands
            echo "Building and deploying to staging..."
    
    deploy_production:
        name: Deploy to Production (Manual Approval)
        runs-on: ubuntu-latest
        needs: [deploy_staging]
    
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
    
        # Add your deployment steps for production here.
        # For example:
        - name: Deploy Production
          run: |
            # Replace with your production deployment commands
            echo "Deploying to production..." 

        
    # Add other jobs for additional environments as needed.
    # For example, you can add a job for a testing environment
    
    

    

